import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { RiExternalLinkLine } from 'react-icons/ri';
import { AiFillGithub, AiFillYoutube } from 'react-icons/ai';
import { SiFreelancer } from 'react-icons/si';
import Image from 'next/image';
import mypic from '../public/dev.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import logo from '../public/net-shinobi.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';

import { useState } from 'react';
import Footer from '../components/Footer';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-4 dark:bg-gray-900 w-screen md:px-20 lg:px-40">
        <section className="min-h-screen mb-10">
          <nav className="py-10 mb-12 flex justify-between items-center ">
            <div className="text-xl font-roboto dark:text-white">
              <Image
                href="/"
                src={logo}
                height={200}
                className="cursor-pointer"
              />
            </div>
            <div className="w-full md:w-1/2">
              <ul className="flex justify-evenly items-center uppercase font-bold mx-2 text-sm md:text-base">
                <li className=" text-black dark:text-white hover:text-yellow-400 mx-2 dark:hover:text-yellow-400 cursor-pointer">
                  <a href="#services">Services </a>
                </li>
                <li className=" text-black dark:text-white  hover:text-yellow-400 mx-2 dark:hover:text-yellow-400 cursor-pointer">
                  <a href="#portfolio">Portfolio</a>
                </li>
                <li>
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl text-yellow-400"
                  />
                </li>

                <li>
                  <a
                    className=" text-black dark:text-white rounded-sm   hover:text-yellow-400 mx-2 dark:hover:text-yellow-400 cursor-pointer"
                    href="#"
                  >
                    RESUME
                  </a>
                </li>
              </ul>
            </div>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Abdul Hamid
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Web Designer & Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-lg max-w-xl mx-auto dark:text-white">
              Freelancer providing services programming and design content
              needs. Join me down below and lets get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a href="https://www.freelancer.com/u/skyrulez" target="_blank">
              <SiFreelancer className="text-blue-400 cursor-pointer hover:text-blue-500" />
            </a>

            <a href="https://github.com/sirsky89" target="_blank">
              <AiFillGithub className="text-gray-700 cursor-pointer hover:text-black dark:text-white dark:hover:text-yellow-200" />
            </a>

            <AiFillYoutube className="text-red-500 cursor-pointer hover:text-red-600" />
          </div>
          <div className="relative flex justify-center items-center mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={mypic} className="mt-10 ml-8" />
          </div>
        </section>
        <section id="services" className="pt-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Service Offered</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance web developer,
              I've done mock assignment for
              <span className="text-teal-500"> Mereka Academy </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center items-center shadow-lg p-10 rounded-xl my-10  dark:bg-teal-500 flex-1  ">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-white">
                Design Tools That I Use
              </h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-teal-500 flex-1">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-white">
                Programming Language and Framework That I Use
              </h4>
              <p className="text-gray-800 py-1">React JS</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">Next Js</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-teal-500 flex-1">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-white">
                Communication Tools That I Use
              </h4>
              <p className="text-gray-800 py-1">Google Meet</p>
              <p className="text-gray-800 py-1">Zoom</p>
              <p className="text-gray-800 py-1">Youtube</p>
              <p className="text-gray-800 py-1">Whatapp</p>
            </div>
          </div>
        </section>
        <section className="py-10" id="portfolio">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 relative">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web1}
              />
              <button className=" top-8 p-1 absolute  bg-green-400 right-5 ">
                <a href="https://akademy-website.vercel.app/" target="_blank">
                  <RiExternalLinkLine />
                </a>
              </button>
            </div>
            <div className="basis-1/3 flex-1 relative">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web2}
              />
              <button className=" top-8 p-1 absolute  bg-green-400 right-5 ">
                <a
                  href="https://sirsky89.github.io/The-Net-Samurai/"
                  target="_blank"
                >
                  <RiExternalLinkLine />
                </a>
              </button>
            </div>
            <div className="basis-1/3 flex-1 relative">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web3}
              />
              <button className=" top-8 p-1 absolute  bg-green-400 right-5 ">
                <a
                  href="https://sirsky89.github.io/Tailwind-Project/"
                  target="_blank"
                >
                  <RiExternalLinkLine />
                </a>
              </button>
            </div>
            <div className="basis-1/3 flex-1 relative">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web4}
              />
              <button className=" top-8 p-1 absolute  bg-green-400 right-5 ">
                <a
                  href="https://sirsky89.github.io/Order-Summary-Component/"
                  target="_blank"
                >
                  <RiExternalLinkLine />
                </a>
              </button>
            </div>
          </div>
        </section>
        <Footer />
      </main>
    </div>
  );
}
